version: "3.9"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - db
            - postgres

    db:
        image: mysql:5.7
        container_name: mysql_container
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db
            PMA_USER: user
            PMA_PASSWORD: test
        depends_on:
            - db

    postgres:
        image: postgres:16
        container_name: postgres_container
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: postgres_db
        ports:
            - "5432:5432"
        volumes:
            - ./pg_dump:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data

volumes:
    mysql_data:
    postgres_data:
